### ISSUE TITLE
The tree structure seems not right

### ISSUE THREAD

**Issue by NightSharp** [piroor/tst-open-bookmarks-as-partial-tree#13]
Here is my bookmarks dir
![屏幕截图 2024-03-16 185032](https://github.com/piroor/tst-open-bookmarks-as-partial-tree/assets/9748063/92c8195b-74e7-4f67-87fd-1b54ad6d3d04)

Here is the opening result
![屏幕截图 2024-03-16 184954](https://github.com/piroor/tst-open-bookmarks-as-partial-tree/assets/9748063/aafc220a-a30c-4b53-8d36-1fdf3512b50a)

the order seems reversed, which don't match the order in bookmarks dir

my "new tab position" (opened by other method) is set to "first child of current".
and I enabled the "auto-group tab"

If I change it to default the result will be more weird

**Comment by NightSharp** [comment]
@piroor

**Comment by piroor** [comment]
I've got different result:
![image](https://github.com/piroor/tst-open-bookmarks-as-partial-tree/assets/70062/d8a8483e-e5d4-443b-bd7a-867f955839fc)

Settings:

* TST options
  * New Tabs not from Existing Tabs
    * Non-blank new tabs
      * Tabs from any other trigger: Open as First Child of the current tab
    * Auto-grouping of tabs
      * Detect tabs opened form a bookmark folder within 100 msec (checked)
      * Auto-group tabs opened at a same from non-bookmark trigger also (checked)

On the other hand, changing the option "Tabs from any other trigger:" to "(no control)" solves the problem for me.
![image](https://github.com/piroor/tst-open-bookmarks-as-partial-tree/assets/70062/ae3c75d1-f358-405f-97a3-2f3adc08b346)

Auto-grouping options look not related and the "Tabs from any other trigger:" options looks the trigger for me. Are auto-grouping options need to be enabled to reproduce the problem, on your case?

**Comment by NightSharp** [comment]
~There seems correct to set the option to no-control except 1 case:~
~items are all the same as "about:blank"~
~and the browser set to my language~
![图片](https://github.com/piroor/tst-open-bookmarks-as-partial-tree/assets/9748063/0dcdce02-7414-4d39-87f2-d584a6a660ef)
this case is related to another setting and I just solve it.
But there is another question

In TST main extension's settings, at the "Context Menu | Bookmarks Context Menu" , existing the similar feature to the "TST Open" extension. However the opening result is a little bit different:
The group tab keep unloaded like the opened bookmarks, which is loaded in the "TST Open" extension

This is the "TST Open" extension
![图片](https://github.com/piroor/tst-open-bookmarks-as-partial-tree/assets/9748063/40425818-6f3a-4821-8fe1-cb34a85c18b7)

This is the main extension
![图片](https://github.com/piroor/tst-open-bookmarks-as-partial-tree/assets/9748063/e0373d4f-988c-496d-af11-325c19c438c1)

**Comment by NightSharp** [comment]
I'm confused, now the result of "TST Open Bookmarks as Partial Tree" turn to this (at the opening first it is right, but quickly it switch to the weird case):
![图片](https://github.com/piroor/tst-open-bookmarks-as-partial-tree/assets/9748063/ac82f8a6-9dbe-49f6-9e47-3dbdd813890d)

The main extension works as before
![图片](https://github.com/piroor/tst-open-bookmarks-as-partial-tree/assets/9748063/35fce26a-fcb7-4396-a6b0-beef6194ab81)

**Comment by NightSharp** [comment]
> I'm confused, now the result of "TST Open Bookmarks as Partial Tree" turn to this (at the opening first it is right, but quickly it switch to the weird case): ![图片](https://private-user-images.githubusercontent.com/9748063/313899942-ac82f8a6-9dbe-49f6-9e47-3dbdd813890d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjE4NjksIm5iZiI6MTcxMDgyMTU2OSwicGF0aCI6Ii85NzQ4MDYzLzMxMzg5OTk0Mi1hYzgyZjhhNi05ZGJlLTQ5ZjYtOWU0Ny0zZGJkZDgxMzg5MGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMDQxMjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzc2OWMyYzc5ZjAzNjVlZDk1YTk0OWY5OGQ5NGZkNjE3ZDNhNjI3ZjZjYzE1NmY1OTFlNmVjMmRjZDNiMzM4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hjYk75rWp783OkD_0XLpNRGMVTKN7L3oj07HcWl_zQM)
> 
> The main extension works as before ![图片](https://private-user-images.githubusercontent.com/9748063/313900552-35fce26a-fcb7-4396-a6b0-beef6194ab81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjE4NjksIm5iZiI6MTcxMDgyMTU2OSwicGF0aCI6Ii85NzQ4MDYzLzMxMzkwMDU1Mi0zNWZjZTI2YS1mY2I3LTQzOTYtYTZiMC1iZWVmNjE5NGFiODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMDQxMjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjJkODBhZTkzMTU0ZTU4MWFiYTNlMDI0MzRhYmU5Yjc2M2ZkNzVjYWJjYThkYzEwMmYzOWYwNTVkMzI4NDY4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jOi3tOxJ3jjx9peDaGtHWv40FaaC8ar84Gpdob2cbhM)

So strange, I changed some settings and it works correct again

**Comment by piroor** [comment]
Anyway this addon creates tabs via `browser.tabs.create()` and TST tries to control positions of new tabs based on its option, as the result a broken tree is produced. We need to use a special API to create tabs without TST's tab control https://github.com/piroor/treestyletab/wiki/API-for-other-addons#open-new-tab-bypassing-tsts-tab-control-behavior instead.

**Comment by piroor** [comment]
The commit ae99cde should fix this.

**Comment by NightSharp** [comment]
> Anyway this addon creates tabs via `browser.tabs.create()` and TST tries to control positions of new tabs based on its option, as the result a broken tree is produced. We need to use a special API to create tabs without TST's tab control https://github.com/piroor/treestyletab/wiki/API-for-other-addons#open-new-tab-bypassing-tsts-tab-control-behavior instead.

Thanks.
Oh, There is 1 more issue
I set the duplicating position to "Sibling Next to the Current".
But when I duplicate a tab, it appears as "First Child of the Current"
btw, I set "browser.tabs.insertAfterCurrent"="true"
though set it to "false" works, but it will break my other actions about tabs

**Comment by piroor** [comment]
> Oh, There is 1 more issue I set the duplicating position to "Sibling Next to the Current". But when I duplicate a tab, it appears as "First Child of the Current" btw, I set "browser.tabs.insertAfterCurrent"="true" though set it to "false" works, but it will break my other actions about tabs

This looks to be a TST issue, Could you create a new issue to https://github.com/piroor/treestyletab/issues for it?

**Comment by NightSharp** [comment]
> > Oh, There is 1 more issue I set the duplicating position to "Sibling Next to the Current". But when I duplicate a tab, it appears as "First Child of the Current" btw, I set "browser.tabs.insertAfterCurrent"="true" though set it to "false" works, but it will break my other actions about tabs
> 
> This looks to be a TST issue, Could you create a new issue to https://github.com/piroor/treestyletab/issues for it?

all right, done.
https://github.com/piroor/treestyletab/issues/3502#issue-2196393112
