### ISSUE TITLE
The default state of Auto-group tab don't follow my TST config (similar to this issue in TST)

### ISSUE THREAD

**Issue by NightSharp** [piroor/tst-open-bookmarks-as-partial-tree#14]
It is similar to 
https://github.com/piroor/treestyletab/issues/3509#issue-2201619566

It has been solved in TST itself, but not this add-on

**Comment by NightSharp** [comment]
@piroor

**Comment by piroor** [comment]
Sorry for my long silence. With the commit 97178c4 now you can change the default behavior of group tabs.

**Comment by piroor** [comment]
Note that it is not synchronized to TST's option automatically and you need to configure it by your hand.

**Comment by NightSharp** [comment]
> Note that it is not synchronized to TST's option automatically and you need to configure it by your hand.

It seems that this extension's version in firefox store is still at 2024-03-26, which haven't fixed this issue yet.
